version: '3.8'

services:
  aws:
    image: amazon/aws-cli:2.0.56
    entrypoint:
      - /bin/bash
#      - /usr/local/bin/aws
    environment:
      PS1: '\n\[\033[1;36m\]\w\[\033[0m\] \$$ ' # double dollar sign required by compose file reference
    volumes:
      - aws-config:/root/.aws
      - ./tools:/tools

  az:
    image: mcr.microsoft.com/azure-cli:2.12.1
    entrypoint:
      - /bin/bash
#      - /usr/local/bin/az
    environment:
      PS1: '\n\[\033[1;36m\]\w\[\033[0m\] \$$ ' # double dollar sign required by compose file reference
    volumes:
      - az-config:/root/.azure
      - ./tools:/tools

  gcp:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:313.0.1-alpine
    entrypoint:
      - /bin/bash
#      - /google-cloud-sdk/bin/gcloud
    environment:
      PS1: '\n\[\033[1;36m\]\w\[\033[0m\] \$$ ' # double dollar sign required by compose file reference
    volumes:
      - gcp-config:/root/.config
      - ./tools:/tools

volumes:
  aws-config:
  az-config:
  gcp-config:
