version: '3.8'

services:
  cloud-cli:
    image: docker.pkg.github.com/informatica-na-presales-ops/cloud-cli/cloud-cli
    build: .
    volumes:
      - aws-credentials:/root/.aws
      - azure-credentials:/root/.azure

  aws:
    image: amazon/aws-cli:2.0.7
    entrypoint:
      - /bin/bash
    environment:
      PS1: '\n\[\033[1;36m\]\w\[\033[0m\] \$$ ' # double dollar sign required by compose file reference
    volumes:
      - aws-credentials:/root/.aws
      - ./tools:/tools

  az:
    image: mcr.microsoft.com/azure-cli:2.11.1
    entrypoint:
      - /bin/bash
#      - /usr/local/bin/az
    environment:
      PS1: '\n\[\033[1;36m\]\w\[\033[0m\] \$$ ' # double dollar sign required by compose file reference
    volumes:
      - azure-credentials:/root/.azure
      - ./tools:/tools

volumes:
  aws-credentials:
  azure-credentials:
